mv ./roman-numerals/.docs/instructions.md ./roman-numerals/
mv ./armstrong-numbers/.docs/instructions.md ./armstrong-numbers/
mv ./difference-of-squares/.docs/instructions.md ./difference-of-squares/
mv ./perfect-numbers/.docs/instructions.md ./perfect-numbers/
mv ./rna-transcription/.docs/instructions.md ./rna-transcription/
mv ./atbash-cipher/.docs/instructions.md ./atbash-cipher/
mv ./trinary/.docs/instructions.md ./trinary/
mv ./bob/.docs/instructions.md ./bob/
mv ./phone-number/.docs/instructions.md ./phone-number/
mv ./anagram/.docs/instructions.md ./anagram/
mv ./two-fer/.docs/instructions.md ./two-fer/
mv ./nucleotide-count/.docs/instructions.md ./nucleotide-count/
mv ./etl/.docs/instructions.md ./etl/
mv ./crypto-square/.docs/instructions.md ./crypto-square/
mv ./gigasecond/.docs/instructions.md ./gigasecond/
mv ./run-length-encoding/.docs/instructions.md ./run-length-encoding/
mv ./hello-world/.docs/instructions.md ./hello-world/
mv ./leap/.docs/instructions.md ./leap/
mv ./hamming/.docs/instructions.md ./hamming/
mv ./luhn/.docs/instructions.md ./luhn/
mv ./grains/.docs/instructions.md ./grains/
mv ./raindrops/.docs/instructions.md ./raindrops/
mv ./acronym/.docs/instructions.md ./acronym/
mv ./robot-name/.docs/instructions.md ./robot-name/
mv ./binary/.docs/instructions.md ./binary/
mv ./word-count/.docs/instructions.md ./word-count/
mv ./allergies/.docs/instructions.md ./allergies/
mv ./pangram/.docs/instructions.md ./pangram/
 
